#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSX.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSX")]
	public partial class QLSXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertHangMuc(HangMuc instance);
    partial void UpdateHangMuc(HangMuc instance);
    partial void DeleteHangMuc(HangMuc instance);
    partial void InsertChiTietHangMuc(ChiTietHangMuc instance);
    partial void UpdateChiTietHangMuc(ChiTietHangMuc instance);
    partial void DeleteChiTietHangMuc(ChiTietHangMuc instance);
    partial void InsertTinhTrangHopDong(TinhTrangHopDong instance);
    partial void UpdateTinhTrangHopDong(TinhTrangHopDong instance);
    partial void DeleteTinhTrangHopDong(TinhTrangHopDong instance);
    partial void InsertCongTrinh(CongTrinh instance);
    partial void UpdateCongTrinh(CongTrinh instance);
    partial void DeleteCongTrinh(CongTrinh instance);
    #endregion
		
		public QLSXDataContext() : 
				base(global::QLSX.Properties.Settings.Default.QLSXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLSXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLSXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<HangMuc> HangMucs
		{
			get
			{
				return this.GetTable<HangMuc>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHangMuc> ChiTietHangMucs
		{
			get
			{
				return this.GetTable<ChiTietHangMuc>();
			}
		}
		
		public System.Data.Linq.Table<TinhTrangHopDong> TinhTrangHopDongs
		{
			get
			{
				return this.GetTable<TinhTrangHopDong>();
			}
		}
		
		public System.Data.Linq.Table<CongTrinh> CongTrinhs
		{
			get
			{
				return this.GetTable<CongTrinh>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMuc_add")]
		public int ChiTietHangMuc_add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMuc", DbType="Int")] System.Nullable<int> maHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenChiTiet", DbType="NVarChar(100)")] string tenChiTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuyCach", DbType="NVarChar(20)")] string quyCach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChieuDai", DbType="Int")] System.Nullable<int> chieuDai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChieuRong", DbType="Int")] System.Nullable<int> chieuRong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TyTrong", DbType="Decimal(18,0)")] System.Nullable<decimal> tyTrong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TLDonVi", DbType="Decimal(18,0)")] System.Nullable<decimal> tLDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(200)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMuc, tenChiTiet, quyCach, chieuDai, chieuRong, tyTrong, soLuong, tLDonVi, donGia, ghiChu, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMuc_delete")]
		public int ChiTietHangMuc_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maChiTietHM)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChiTietHM);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMuc_getList")]
		public ISingleResult<ChiTietHangMuc> ChiTietHangMuc_getList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maChiTietHM, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChiTietHM, maHangMuc, searchKey);
			return ((ISingleResult<ChiTietHangMuc>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMuc_delete")]
		public int HangMuc_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMuc", DbType="Int")] System.Nullable<int> maHangMuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMuc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMuc_update")]
		public int HangMuc_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMuc", DbType="Int")] System.Nullable<int> maHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHangMuc", DbType="NVarChar(200)")] string tenHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongTrinh", DbType="Int")] System.Nullable<int> maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMuc, tenHangMuc, maCongTrinh, maHieuCT, soLuong, donGia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_add")]
		public int KhachHang_add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenKhachHang", DbType="NVarChar(200)")] string tenKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(200)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DienThoai", DbType="NVarChar(20)")] string dienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="NVarChar(20)")] string fax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="NVarChar(100)")] string website, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenKhachHang, diaChi, dienThoai, fax, email, website, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_delete")]
		public int KhachHang_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_getList")]
		public ISingleResult<KhachHang> KhachHang_getList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeySearch", DbType="NVarChar(200)")] string keySearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang, keySearch);
			return ((ISingleResult<KhachHang>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KhachHang_update")]
		public int KhachHang_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenKhachHang", DbType="NVarChar(200)")] string tenKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DiaChi", DbType="NVarChar(200)")] string diaChi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DienThoai", DbType="NVarChar(20)")] string dienThoai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="NVarChar(20)")] string fax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Website", DbType="NVarChar(100)")] string website)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang, tenKhachHang, diaChi, dienThoai, fax, email, website);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMuc_getList")]
		public ISingleResult<HangMuc> HangMuc_getList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMuc", DbType="Int")] System.Nullable<int> maHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongTrinh", DbType="Int")] System.Nullable<int> maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMuc, maCongTrinh, maHieuCT, searchKey);
			return ((ISingleResult<HangMuc>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMuc_update")]
		public int ChiTietHangMuc_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maChiTietHM, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMuc", DbType="Int")] System.Nullable<int> maHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenChiTiet", DbType="NVarChar(100)")] string tenChiTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuyCach", DbType="NVarChar(20)")] string quyCach, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChieuDai", DbType="Int")] System.Nullable<int> chieuDai, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChieuRong", DbType="Int")] System.Nullable<int> chieuRong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TyTrong", DbType="Decimal(18,0)")] System.Nullable<decimal> tyTrong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TLDonVi", DbType="Decimal(18,0)")] System.Nullable<decimal> tLDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(200)")] string ghiChu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChiTietHM, maHangMuc, tenChiTiet, quyCach, chieuDai, chieuRong, tyTrong, soLuong, tLDonVi, donGia, ghiChu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.TinhTrangHopDong_getList")]
		public ISingleResult<TinhTrangHopDong> TinhTrangHopDong_getList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchKey);
			return ((ISingleResult<TinhTrangHopDong>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMuc_add")]
		public int HangMuc_add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHangMuc", DbType="NVarChar(200)")] string tenHangMuc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaCongTrinh", DbType="Int")] System.Nullable<int> maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> maHangMuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenHangMuc, maCongTrinh, maHieuCT, soLuong, donGia, nguoiTao, maHangMuc);
			maHangMuc = ((System.Nullable<int>)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_add")]
		public int CongTrinh_add([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tenCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string soHopDong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngayKy, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngayBatDauCT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngayKetThucCT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string maTinhTrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(18,0)")] System.Nullable<decimal> giaTriHD, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string nguoiTao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> maCongTrinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenCongTrinh, maHieuCT, soHopDong, maKhachHang, ngayKy, ngayBatDauCT, ngayKetThucCT, maTinhTrang, giaTriHD, ghiChu, nguoiTao, maCongTrinh);
			maCongTrinh = ((System.Nullable<int>)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_delete")]
		public int CongTrinh_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maCongTrinh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_update")]
		public int CongTrinh_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCongTrinh", DbType="NVarChar(200)")] string tenCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoHopDong", DbType="NChar(10)")] string soHopDong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKy", DbType="DateTime")] System.Nullable<System.DateTime> ngayKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayBatDauCT", DbType="DateTime")] System.Nullable<System.DateTime> ngayBatDauCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKetThucCT", DbType="DateTime")] System.Nullable<System.DateTime> ngayKetThucCT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string maTinhTrang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTriHD", DbType="Decimal(18,0)")] System.Nullable<decimal> giaTriHD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(MAX)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrongLuongTK", DbType="Decimal(18,0)")] System.Nullable<decimal> trongLuongTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrongLuongTT", DbType="Decimal(18,0)")] System.Nullable<decimal> trongLuongTT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoanCong", DbType="Decimal(18,0)")] System.Nullable<decimal> hoanCong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuyetToanKH", DbType="Decimal(18,0)")] System.Nullable<decimal> quyetToanKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh, tenCongTrinh, maHieuCT, soHopDong, maKhachHang, ngayKy, ngayBatDauCT, ngayKetThucCT, maTinhTrang, giaTriHD, ghiChu, trongLuongTK, trongLuongTT, hoanCong, quyetToanKH);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_getList")]
		public ISingleResult<CongTrinh> CongTrinh_getList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string maTinhTrang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="DateTime")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="DateTime")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCongTrinh, maKhachHang, maTinhTrang, tuNgay, denNgay, searchKey);
			return ((ISingleResult<CongTrinh>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhachHang;
		
		private string _TenKhachHang;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _Fax;
		
		private string _Email;
		
		private string _Website;
		
		private string _NguoiTao;
		
		private System.DateTime _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="NVarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangMuc")]
	public partial class HangMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHangMuc;
		
		private string _TenHangMuc;
		
		private int _MaCongTrinh;
		
		private string _MaHieuCT;
		
		private int _SoLuong;
		
		private System.Nullable<decimal> _DonGia;
		
		private string _NguoiTao;
		
		private System.DateTime _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangMucChanging(int value);
    partial void OnMaHangMucChanged();
    partial void OnTenHangMucChanging(string value);
    partial void OnTenHangMucChanged();
    partial void OnMaCongTrinhChanging(int value);
    partial void OnMaCongTrinhChanged();
    partial void OnMaHieuCTChanging(string value);
    partial void OnMaHieuCTChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<decimal> value);
    partial void OnDonGiaChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public HangMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangMuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHangMuc
		{
			get
			{
				return this._MaHangMuc;
			}
			set
			{
				if ((this._MaHangMuc != value))
				{
					this.OnMaHangMucChanging(value);
					this.SendPropertyChanging();
					this._MaHangMuc = value;
					this.SendPropertyChanged("MaHangMuc");
					this.OnMaHangMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHangMuc", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenHangMuc
		{
			get
			{
				return this._TenHangMuc;
			}
			set
			{
				if ((this._TenHangMuc != value))
				{
					this.OnTenHangMucChanging(value);
					this.SendPropertyChanging();
					this._TenHangMuc = value;
					this.SendPropertyChanged("TenHangMuc");
					this.OnTenHangMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTrinh", DbType="Int NOT NULL")]
		public int MaCongTrinh
		{
			get
			{
				return this._MaCongTrinh;
			}
			set
			{
				if ((this._MaCongTrinh != value))
				{
					this.OnMaCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._MaCongTrinh = value;
					this.SendPropertyChanged("MaCongTrinh");
					this.OnMaCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaHieuCT
		{
			get
			{
				return this._MaHieuCT;
			}
			set
			{
				if ((this._MaHieuCT != value))
				{
					this.OnMaHieuCTChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCT = value;
					this.SendPropertyChanged("MaHieuCT");
					this.OnMaHieuCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHangMuc")]
	public partial class ChiTietHangMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietHM;
		
		private int _MaHangMuc;
		
		private string _TenChiTiet;
		
		private string _QuyCach;
		
		private System.Nullable<int> _ChieuDai;
		
		private System.Nullable<int> _ChieuRong;
		
		private System.Nullable<decimal> _TyTrong;
		
		private int _SoLuong;
		
		private decimal _TLDonVi;
		
		private decimal _DonGia;
		
		private string _GhiChu;
		
		private string _NguoiTao;
		
		private System.DateTime _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietHMChanging(int value);
    partial void OnMaChiTietHMChanged();
    partial void OnMaHangMucChanging(int value);
    partial void OnMaHangMucChanged();
    partial void OnTenChiTietChanging(string value);
    partial void OnTenChiTietChanged();
    partial void OnQuyCachChanging(string value);
    partial void OnQuyCachChanged();
    partial void OnChieuDaiChanging(System.Nullable<int> value);
    partial void OnChieuDaiChanged();
    partial void OnChieuRongChanging(System.Nullable<int> value);
    partial void OnChieuRongChanged();
    partial void OnTyTrongChanging(System.Nullable<decimal> value);
    partial void OnTyTrongChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnTLDonViChanging(decimal value);
    partial void OnTLDonViChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public ChiTietHangMuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietHM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietHM
		{
			get
			{
				return this._MaChiTietHM;
			}
			set
			{
				if ((this._MaChiTietHM != value))
				{
					this.OnMaChiTietHMChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietHM = value;
					this.SendPropertyChanged("MaChiTietHM");
					this.OnMaChiTietHMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangMuc", DbType="Int NOT NULL")]
		public int MaHangMuc
		{
			get
			{
				return this._MaHangMuc;
			}
			set
			{
				if ((this._MaHangMuc != value))
				{
					this.OnMaHangMucChanging(value);
					this.SendPropertyChanging();
					this._MaHangMuc = value;
					this.SendPropertyChanged("MaHangMuc");
					this.OnMaHangMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChiTiet", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenChiTiet
		{
			get
			{
				return this._TenChiTiet;
			}
			set
			{
				if ((this._TenChiTiet != value))
				{
					this.OnTenChiTietChanging(value);
					this.SendPropertyChanging();
					this._TenChiTiet = value;
					this.SendPropertyChanged("TenChiTiet");
					this.OnTenChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyCach", DbType="NVarChar(20)")]
		public string QuyCach
		{
			get
			{
				return this._QuyCach;
			}
			set
			{
				if ((this._QuyCach != value))
				{
					this.OnQuyCachChanging(value);
					this.SendPropertyChanging();
					this._QuyCach = value;
					this.SendPropertyChanged("QuyCach");
					this.OnQuyCachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuDai", DbType="Int")]
		public System.Nullable<int> ChieuDai
		{
			get
			{
				return this._ChieuDai;
			}
			set
			{
				if ((this._ChieuDai != value))
				{
					this.OnChieuDaiChanging(value);
					this.SendPropertyChanging();
					this._ChieuDai = value;
					this.SendPropertyChanged("ChieuDai");
					this.OnChieuDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuRong", DbType="Int")]
		public System.Nullable<int> ChieuRong
		{
			get
			{
				return this._ChieuRong;
			}
			set
			{
				if ((this._ChieuRong != value))
				{
					this.OnChieuRongChanging(value);
					this.SendPropertyChanging();
					this._ChieuRong = value;
					this.SendPropertyChanged("ChieuRong");
					this.OnChieuRongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TyTrong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TyTrong
		{
			get
			{
				return this._TyTrong;
			}
			set
			{
				if ((this._TyTrong != value))
				{
					this.OnTyTrongChanging(value);
					this.SendPropertyChanging();
					this._TyTrong = value;
					this.SendPropertyChanged("TyTrong");
					this.OnTyTrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLDonVi", DbType="Decimal(18,0) NOT NULL")]
		public decimal TLDonVi
		{
			get
			{
				return this._TLDonVi;
			}
			set
			{
				if ((this._TLDonVi != value))
				{
					this.OnTLDonViChanging(value);
					this.SendPropertyChanging();
					this._TLDonVi = value;
					this.SendPropertyChanged("TLDonVi");
					this.OnTLDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0) NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinhTrangHopDong")]
	public partial class TinhTrangHopDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinhTrang;
		
		private string _TenTinhTrang;
		
		private System.Nullable<int> _SapXep;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhTrangChanging(string value);
    partial void OnMaTinhTrangChanged();
    partial void OnTenTinhTrangChanging(string value);
    partial void OnTenTinhTrangChanged();
    partial void OnSapXepChanging(System.Nullable<int> value);
    partial void OnSapXepChanged();
    #endregion
		
		public TinhTrangHopDong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrang", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinhTrang
		{
			get
			{
				return this._MaTinhTrang;
			}
			set
			{
				if ((this._MaTinhTrang != value))
				{
					this.OnMaTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrang = value;
					this.SendPropertyChanged("MaTinhTrang");
					this.OnMaTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTinhTrang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTinhTrang
		{
			get
			{
				return this._TenTinhTrang;
			}
			set
			{
				if ((this._TenTinhTrang != value))
				{
					this.OnTenTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TenTinhTrang = value;
					this.SendPropertyChanged("TenTinhTrang");
					this.OnTenTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SapXep", DbType="Int")]
		public System.Nullable<int> SapXep
		{
			get
			{
				return this._SapXep;
			}
			set
			{
				if ((this._SapXep != value))
				{
					this.OnSapXepChanging(value);
					this.SendPropertyChanging();
					this._SapXep = value;
					this.SendPropertyChanged("SapXep");
					this.OnSapXepChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh")]
	public partial class CongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCongTrinh;
		
		private string _TenCongTrinh;
		
		private string _MaHieuCT;
		
		private string _SoHopDong;
		
		private int _MaKhachHang;
		
		private System.DateTime _NgayKy;
		
		private System.Nullable<System.DateTime> _NgayBatDauCT;
		
		private System.Nullable<System.DateTime> _NgayKetThucCT;
		
		private string _MaTinhTrang;
		
		private System.Nullable<decimal> _GiaTriHD;
		
		private string _GhiChu;
		
		private System.DateTime _NgayTao;
		
		private string _NguoiTao;
		
		private System.Nullable<decimal> _TrongLuongTK;
		
		private System.Nullable<decimal> _TrongLuongTT;
		
		private System.Nullable<decimal> _HoanCong;
		
		private System.Nullable<decimal> _QuyetToanKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCongTrinhChanging(int value);
    partial void OnMaCongTrinhChanged();
    partial void OnTenCongTrinhChanging(string value);
    partial void OnTenCongTrinhChanged();
    partial void OnMaHieuCTChanging(string value);
    partial void OnMaHieuCTChanged();
    partial void OnSoHopDongChanging(string value);
    partial void OnSoHopDongChanged();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnNgayKyChanging(System.DateTime value);
    partial void OnNgayKyChanged();
    partial void OnNgayBatDauCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauCTChanged();
    partial void OnNgayKetThucCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucCTChanged();
    partial void OnMaTinhTrangChanging(string value);
    partial void OnMaTinhTrangChanged();
    partial void OnGiaTriHDChanging(System.Nullable<decimal> value);
    partial void OnGiaTriHDChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnTrongLuongTKChanging(System.Nullable<decimal> value);
    partial void OnTrongLuongTKChanged();
    partial void OnTrongLuongTTChanging(System.Nullable<decimal> value);
    partial void OnTrongLuongTTChanged();
    partial void OnHoanCongChanging(System.Nullable<decimal> value);
    partial void OnHoanCongChanged();
    partial void OnQuyetToanKHChanging(System.Nullable<decimal> value);
    partial void OnQuyetToanKHChanged();
    #endregion
		
		public CongTrinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongTrinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCongTrinh
		{
			get
			{
				return this._MaCongTrinh;
			}
			set
			{
				if ((this._MaCongTrinh != value))
				{
					this.OnMaCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._MaCongTrinh = value;
					this.SendPropertyChanged("MaCongTrinh");
					this.OnMaCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this.OnTenCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._TenCongTrinh = value;
					this.SendPropertyChanged("TenCongTrinh");
					this.OnTenCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaHieuCT
		{
			get
			{
				return this._MaHieuCT;
			}
			set
			{
				if ((this._MaHieuCT != value))
				{
					this.OnMaHieuCTChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCT = value;
					this.SendPropertyChanged("MaHieuCT");
					this.OnMaHieuCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHopDong", DbType="NChar(10)")]
		public string SoHopDong
		{
			get
			{
				return this._SoHopDong;
			}
			set
			{
				if ((this._SoHopDong != value))
				{
					this.OnSoHopDongChanging(value);
					this.SendPropertyChanging();
					this._SoHopDong = value;
					this.SendPropertyChanged("SoHopDong");
					this.OnSoHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int NOT NULL")]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKy", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKy
		{
			get
			{
				return this._NgayKy;
			}
			set
			{
				if ((this._NgayKy != value))
				{
					this.OnNgayKyChanging(value);
					this.SendPropertyChanging();
					this._NgayKy = value;
					this.SendPropertyChanged("NgayKy");
					this.OnNgayKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDauCT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBatDauCT
		{
			get
			{
				return this._NgayBatDauCT;
			}
			set
			{
				if ((this._NgayBatDauCT != value))
				{
					this.OnNgayBatDauCTChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDauCT = value;
					this.SendPropertyChanged("NgayBatDauCT");
					this.OnNgayBatDauCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThucCT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetThucCT
		{
			get
			{
				return this._NgayKetThucCT;
			}
			set
			{
				if ((this._NgayKetThucCT != value))
				{
					this.OnNgayKetThucCTChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThucCT = value;
					this.SendPropertyChanged("NgayKetThucCT");
					this.OnNgayKetThucCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrang", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MaTinhTrang
		{
			get
			{
				return this._MaTinhTrang;
			}
			set
			{
				if ((this._MaTinhTrang != value))
				{
					this.OnMaTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrang = value;
					this.SendPropertyChanged("MaTinhTrang");
					this.OnMaTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaTriHD
		{
			get
			{
				return this._GiaTriHD;
			}
			set
			{
				if ((this._GiaTriHD != value))
				{
					this.OnGiaTriHDChanging(value);
					this.SendPropertyChanging();
					this._GiaTriHD = value;
					this.SendPropertyChanged("GiaTriHD");
					this.OnGiaTriHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongLuongTK", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TrongLuongTK
		{
			get
			{
				return this._TrongLuongTK;
			}
			set
			{
				if ((this._TrongLuongTK != value))
				{
					this.OnTrongLuongTKChanging(value);
					this.SendPropertyChanging();
					this._TrongLuongTK = value;
					this.SendPropertyChanged("TrongLuongTK");
					this.OnTrongLuongTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongLuongTT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TrongLuongTT
		{
			get
			{
				return this._TrongLuongTT;
			}
			set
			{
				if ((this._TrongLuongTT != value))
				{
					this.OnTrongLuongTTChanging(value);
					this.SendPropertyChanging();
					this._TrongLuongTT = value;
					this.SendPropertyChanged("TrongLuongTT");
					this.OnTrongLuongTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoanCong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> HoanCong
		{
			get
			{
				return this._HoanCong;
			}
			set
			{
				if ((this._HoanCong != value))
				{
					this.OnHoanCongChanging(value);
					this.SendPropertyChanging();
					this._HoanCong = value;
					this.SendPropertyChanged("HoanCong");
					this.OnHoanCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyetToanKH", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QuyetToanKH
		{
			get
			{
				return this._QuyetToanKH;
			}
			set
			{
				if ((this._QuyetToanKH != value))
				{
					this.OnQuyetToanKHChanging(value);
					this.SendPropertyChanging();
					this._QuyetToanKH = value;
					this.SendPropertyChanged("QuyetToanKH");
					this.OnQuyetToanKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
