#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanXuat.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSX")]
	public partial class CongTrinhDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCongTrinh(CongTrinh instance);
    partial void UpdateCongTrinh(CongTrinh instance);
    partial void DeleteCongTrinh(CongTrinh instance);
    #endregion
		
		public CongTrinhDataContext() : 
				base(global::QuanLySanXuat.Properties.Settings.Default.QLSXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CongTrinhDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CongTrinhDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CongTrinhDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CongTrinhDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CongTrinh> CongTrinhs
		{
			get
			{
				return this.GetTable<CongTrinh>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_add")]
		public int CongTrinh_add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCongTrinh", DbType="NVarChar(200)")] string tenCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoHopDong", DbType="NChar(10)")] string soHopDong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKy", DbType="DateTime")] System.Nullable<System.DateTime> ngayKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayBatDauCT", DbType="DateTime")] System.Nullable<System.DateTime> ngayBatDauCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKetThucCT", DbType="DateTime")] System.Nullable<System.DateTime> ngayKetThucCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TinhTrangID", DbType="Int")] System.Nullable<int> tinhTrangID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTriHD", DbType="Decimal(18,0)")] System.Nullable<decimal> giaTriHD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(MAX)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenCongTrinh, maHieuCT, soHopDong, maKhachHang, ngayKy, ngayBatDauCT, ngayKetThucCT, tinhTrangID, giaTriHD, ghiChu, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_Copy_ThietKe2ThucTe")]
		public int CongTrinh_Copy_ThietKe2ThucTe([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhID, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_delete")]
		public int CongTrinh_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_getList")]
		public ISingleResult<CongTrinh> CongTrinh_getList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TinhTrangID", DbType="Int")] System.Nullable<int> tinhTrangID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TuNgay", DbType="DateTime")] System.Nullable<System.DateTime> tuNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DenNgay", DbType="DateTime")] System.Nullable<System.DateTime> denNgay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchKey", DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhID, maKhachHang, tinhTrangID, tuNgay, denNgay, searchKey);
			return ((ISingleResult<CongTrinh>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CongTrinh_update")]
		public int CongTrinh_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenCongTrinh", DbType="NVarChar(200)")] string tenCongTrinh, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoHopDong", DbType="NChar(10)")] string soHopDong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="Int")] System.Nullable<int> maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKy", DbType="DateTime")] System.Nullable<System.DateTime> ngayKy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayBatDauCT", DbType="DateTime")] System.Nullable<System.DateTime> ngayBatDauCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NgayKetThucCT", DbType="DateTime")] System.Nullable<System.DateTime> ngayKetThucCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TinhTrangID", DbType="Int")] System.Nullable<int> tinhTrangID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTriHD", DbType="Decimal(18,0)")] System.Nullable<decimal> giaTriHD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(MAX)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrongLuongTK", DbType="Decimal(18,0)")] System.Nullable<decimal> trongLuongTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrongLuongTT", DbType="Decimal(18,0)")] System.Nullable<decimal> trongLuongTT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HoanCong", DbType="Decimal(18,0)")] System.Nullable<decimal> hoanCong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuyetToanKH", DbType="Decimal(18,0)")] System.Nullable<decimal> quyetToanKH)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), congTrinhID, tenCongTrinh, maHieuCT, soHopDong, maKhachHang, ngayKy, ngayBatDauCT, ngayKetThucCT, tinhTrangID, giaTriHD, ghiChu, trongLuongTK, trongLuongTT, hoanCong, quyetToanKH);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CongTrinh")]
	public partial class CongTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CongTrinhID;
		
		private string _TenCongTrinh;
		
		private string _MaHieuCT;
		
		private string _SoHopDong;
		
		private int _MaKhachHang;
		
		private System.DateTime _NgayKy;
		
		private System.Nullable<System.DateTime> _NgayBatDauCT;
		
		private System.Nullable<System.DateTime> _NgayKetThucCT;
		
		private int _TinhTrangID;
		
		private System.Nullable<decimal> _GiaTriHD;
		
		private string _GhiChu;
		
		private System.DateTime _NgayTao;
		
		private string _NguoiTao;
		
		private System.Nullable<decimal> _TrongLuongTK;
		
		private System.Nullable<decimal> _TrongLuongTT;
		
		private System.Nullable<decimal> _HoanCong;
		
		private System.Nullable<decimal> _QuyetToanKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCongTrinhIDChanging(int value);
    partial void OnCongTrinhIDChanged();
    partial void OnTenCongTrinhChanging(string value);
    partial void OnTenCongTrinhChanged();
    partial void OnMaHieuCTChanging(string value);
    partial void OnMaHieuCTChanged();
    partial void OnSoHopDongChanging(string value);
    partial void OnSoHopDongChanged();
    partial void OnMaKhachHangChanging(int value);
    partial void OnMaKhachHangChanged();
    partial void OnNgayKyChanging(System.DateTime value);
    partial void OnNgayKyChanged();
    partial void OnNgayBatDauCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauCTChanged();
    partial void OnNgayKetThucCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKetThucCTChanged();
    partial void OnTinhTrangIDChanging(int value);
    partial void OnTinhTrangIDChanged();
    partial void OnGiaTriHDChanging(System.Nullable<decimal> value);
    partial void OnGiaTriHDChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnTrongLuongTKChanging(System.Nullable<decimal> value);
    partial void OnTrongLuongTKChanged();
    partial void OnTrongLuongTTChanging(System.Nullable<decimal> value);
    partial void OnTrongLuongTTChanged();
    partial void OnHoanCongChanging(System.Nullable<decimal> value);
    partial void OnHoanCongChanged();
    partial void OnQuyetToanKHChanging(System.Nullable<decimal> value);
    partial void OnQuyetToanKHChanged();
    #endregion
		
		public CongTrinh()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CongTrinhID
		{
			get
			{
				return this._CongTrinhID;
			}
			set
			{
				if ((this._CongTrinhID != value))
				{
					this.OnCongTrinhIDChanging(value);
					this.SendPropertyChanging();
					this._CongTrinhID = value;
					this.SendPropertyChanged("CongTrinhID");
					this.OnCongTrinhIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongTrinh", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenCongTrinh
		{
			get
			{
				return this._TenCongTrinh;
			}
			set
			{
				if ((this._TenCongTrinh != value))
				{
					this.OnTenCongTrinhChanging(value);
					this.SendPropertyChanging();
					this._TenCongTrinh = value;
					this.SendPropertyChanged("TenCongTrinh");
					this.OnTenCongTrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaHieuCT
		{
			get
			{
				return this._MaHieuCT;
			}
			set
			{
				if ((this._MaHieuCT != value))
				{
					this.OnMaHieuCTChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCT = value;
					this.SendPropertyChanged("MaHieuCT");
					this.OnMaHieuCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHopDong", DbType="NChar(10)")]
		public string SoHopDong
		{
			get
			{
				return this._SoHopDong;
			}
			set
			{
				if ((this._SoHopDong != value))
				{
					this.OnSoHopDongChanging(value);
					this.SendPropertyChanging();
					this._SoHopDong = value;
					this.SendPropertyChanged("SoHopDong");
					this.OnSoHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="Int NOT NULL")]
		public int MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKy", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKy
		{
			get
			{
				return this._NgayKy;
			}
			set
			{
				if ((this._NgayKy != value))
				{
					this.OnNgayKyChanging(value);
					this.SendPropertyChanging();
					this._NgayKy = value;
					this.SendPropertyChanged("NgayKy");
					this.OnNgayKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDauCT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBatDauCT
		{
			get
			{
				return this._NgayBatDauCT;
			}
			set
			{
				if ((this._NgayBatDauCT != value))
				{
					this.OnNgayBatDauCTChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDauCT = value;
					this.SendPropertyChanged("NgayBatDauCT");
					this.OnNgayBatDauCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThucCT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKetThucCT
		{
			get
			{
				return this._NgayKetThucCT;
			}
			set
			{
				if ((this._NgayKetThucCT != value))
				{
					this.OnNgayKetThucCTChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThucCT = value;
					this.SendPropertyChanged("NgayKetThucCT");
					this.OnNgayKetThucCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangID", DbType="Int NOT NULL")]
		public int TinhTrangID
		{
			get
			{
				return this._TinhTrangID;
			}
			set
			{
				if ((this._TinhTrangID != value))
				{
					this.OnTinhTrangIDChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangID = value;
					this.SendPropertyChanged("TinhTrangID");
					this.OnTinhTrangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHD", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GiaTriHD
		{
			get
			{
				return this._GiaTriHD;
			}
			set
			{
				if ((this._GiaTriHD != value))
				{
					this.OnGiaTriHDChanging(value);
					this.SendPropertyChanging();
					this._GiaTriHD = value;
					this.SendPropertyChanged("GiaTriHD");
					this.OnGiaTriHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongLuongTK", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TrongLuongTK
		{
			get
			{
				return this._TrongLuongTK;
			}
			set
			{
				if ((this._TrongLuongTK != value))
				{
					this.OnTrongLuongTKChanging(value);
					this.SendPropertyChanging();
					this._TrongLuongTK = value;
					this.SendPropertyChanged("TrongLuongTK");
					this.OnTrongLuongTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrongLuongTT", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> TrongLuongTT
		{
			get
			{
				return this._TrongLuongTT;
			}
			set
			{
				if ((this._TrongLuongTT != value))
				{
					this.OnTrongLuongTTChanging(value);
					this.SendPropertyChanging();
					this._TrongLuongTT = value;
					this.SendPropertyChanged("TrongLuongTT");
					this.OnTrongLuongTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoanCong", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> HoanCong
		{
			get
			{
				return this._HoanCong;
			}
			set
			{
				if ((this._HoanCong != value))
				{
					this.OnHoanCongChanging(value);
					this.SendPropertyChanging();
					this._HoanCong = value;
					this.SendPropertyChanged("HoanCong");
					this.OnHoanCongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyetToanKH", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QuyetToanKH
		{
			get
			{
				return this._QuyetToanKH;
			}
			set
			{
				if ((this._QuyetToanKH != value))
				{
					this.OnQuyetToanKHChanging(value);
					this.SendPropertyChanging();
					this._QuyetToanKH = value;
					this.SendPropertyChanged("QuyetToanKH");
					this.OnQuyetToanKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
