#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySanXuat.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSX")]
	public partial class HangMucTKDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietHangMucTK(ChiTietHangMucTK instance);
    partial void UpdateChiTietHangMucTK(ChiTietHangMucTK instance);
    partial void DeleteChiTietHangMucTK(ChiTietHangMucTK instance);
    partial void InsertHangMucTK(HangMucTK instance);
    partial void UpdateHangMucTK(HangMucTK instance);
    partial void DeleteHangMucTK(HangMucTK instance);
    #endregion
		
		public HangMucTKDataContext() : 
				base(global::QuanLySanXuat.Properties.Settings.Default.QLSXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HangMucTKDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HangMucTKDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HangMucTKDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HangMucTKDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHangMucTK> ChiTietHangMucTKs
		{
			get
			{
				return this.GetTable<ChiTietHangMucTK>();
			}
		}
		
		public System.Data.Linq.Table<HangMucTK> HangMucTKs
		{
			get
			{
				return this.GetTable<HangMucTK>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMucTK_add")]
		public int ChiTietHangMucTK_add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMucTK", DbType="Int")] System.Nullable<int> maHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKetCauChiTiet", DbType="Int")] System.Nullable<int> maKetCauChiTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TLDonVi", DbType="Decimal(18,0)")] System.Nullable<decimal> tLDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TLTong", DbType="Decimal(18,0)")] System.Nullable<decimal> tLTong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTri", DbType="Decimal(18,0)")] System.Nullable<decimal> giaTri, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(200)")] string ghiChu, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMucTK, maKetCauChiTiet, soLuong, tLDonVi, tLTong, donGia, giaTri, ghiChu, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMucTK_update")]
		public int ChiTietHangMucTK_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maChiTietTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMucTK", DbType="Int")] System.Nullable<int> maHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKetCauChiTiet", DbType="Int")] System.Nullable<int> maKetCauChiTiet, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TLDonVi", DbType="Decimal(18,0)")] System.Nullable<decimal> tLDonVi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TLTong", DbType="Decimal(18,0)")] System.Nullable<decimal> tLTong, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DonGia", DbType="Decimal(18,0)")] System.Nullable<decimal> donGia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GiaTri", DbType="Decimal(18,0)")] System.Nullable<decimal> giaTri, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GhiChu", DbType="NVarChar(200)")] string ghiChu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChiTietTK, maHangMucTK, maKetCauChiTiet, soLuong, tLDonVi, tLTong, donGia, giaTri, ghiChu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMucTK_delete")]
		public int ChiTietHangMucTK_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maChiTietTK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChiTietTK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTietHangMucTK_getList")]
		public ISingleResult<ChiTietHangMucTK> ChiTietHangMucTK_getList([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maChiTietTK, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maChiTietTK, maHangMucTK, searchKey);
			return ((ISingleResult<ChiTietHangMucTK>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMucTK_add")]
		public int HangMucTK_add([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHangMucTK", DbType="NVarChar(200)")] string tenHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NguoiTao", DbType="NVarChar(20)")] string nguoiTao)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenHangMucTK, congTrinhID, maHieuCT, nguoiTao);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMucTK_update")]
		public int HangMucTK_update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMucTK", DbType="Int")] System.Nullable<int> maHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TenHangMucTK", DbType="NVarChar(200)")] string tenHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMucTK, tenHangMucTK, congTrinhID, maHieuCT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMucTK_delete")]
		public int HangMucTK_delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMucTK", DbType="Int")] System.Nullable<int> maHangMucTK)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMucTK);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HangMucTK_getList")]
		public ISingleResult<HangMucTK> HangMucTK_getList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHangMucTK", DbType="Int")] System.Nullable<int> maHangMucTK, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CongTrinhID", DbType="Int")] System.Nullable<int> congTrinhID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaHieuCT", DbType="NVarChar(20)")] string maHieuCT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string searchKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maHangMucTK, congTrinhID, maHieuCT, searchKey);
			return ((ISingleResult<HangMucTK>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHangMucTK")]
	public partial class ChiTietHangMucTK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietTK;
		
		private int _MaHangMucTK;
		
		private int _MaKetCauChiTiet;
		
		private int _SoLuong;
		
		private decimal _TLDonVi;
		
		private decimal _TLTong;
		
		private decimal _DonGia;
		
		private decimal _GiaTri;
		
		private string _GhiChu;
		
		private string _NguoiTao;
		
		private System.DateTime _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietTKChanging(int value);
    partial void OnMaChiTietTKChanged();
    partial void OnMaHangMucTKChanging(int value);
    partial void OnMaHangMucTKChanged();
    partial void OnMaKetCauChiTietChanging(int value);
    partial void OnMaKetCauChiTietChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnTLDonViChanging(decimal value);
    partial void OnTLDonViChanged();
    partial void OnTLTongChanging(decimal value);
    partial void OnTLTongChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnGiaTriChanging(decimal value);
    partial void OnGiaTriChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public ChiTietHangMucTK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietTK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietTK
		{
			get
			{
				return this._MaChiTietTK;
			}
			set
			{
				if ((this._MaChiTietTK != value))
				{
					this.OnMaChiTietTKChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietTK = value;
					this.SendPropertyChanged("MaChiTietTK");
					this.OnMaChiTietTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangMucTK", DbType="Int NOT NULL")]
		public int MaHangMucTK
		{
			get
			{
				return this._MaHangMucTK;
			}
			set
			{
				if ((this._MaHangMucTK != value))
				{
					this.OnMaHangMucTKChanging(value);
					this.SendPropertyChanging();
					this._MaHangMucTK = value;
					this.SendPropertyChanged("MaHangMucTK");
					this.OnMaHangMucTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKetCauChiTiet", DbType="Int NOT NULL")]
		public int MaKetCauChiTiet
		{
			get
			{
				return this._MaKetCauChiTiet;
			}
			set
			{
				if ((this._MaKetCauChiTiet != value))
				{
					this.OnMaKetCauChiTietChanging(value);
					this.SendPropertyChanging();
					this._MaKetCauChiTiet = value;
					this.SendPropertyChanged("MaKetCauChiTiet");
					this.OnMaKetCauChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLDonVi", DbType="Decimal(18,0) NOT NULL")]
		public decimal TLDonVi
		{
			get
			{
				return this._TLDonVi;
			}
			set
			{
				if ((this._TLDonVi != value))
				{
					this.OnTLDonViChanging(value);
					this.SendPropertyChanging();
					this._TLDonVi = value;
					this.SendPropertyChanged("TLDonVi");
					this.OnTLDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TLTong", DbType="Decimal(18,0) NOT NULL")]
		public decimal TLTong
		{
			get
			{
				return this._TLTong;
			}
			set
			{
				if ((this._TLTong != value))
				{
					this.OnTLTongChanging(value);
					this.SendPropertyChanging();
					this._TLTong = value;
					this.SendPropertyChanged("TLTong");
					this.OnTLTongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Decimal(18,0) NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTri", DbType="Decimal(18,0) NOT NULL")]
		public decimal GiaTri
		{
			get
			{
				return this._GiaTri;
			}
			set
			{
				if ((this._GiaTri != value))
				{
					this.OnGiaTriChanging(value);
					this.SendPropertyChanging();
					this._GiaTri = value;
					this.SendPropertyChanged("GiaTri");
					this.OnGiaTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangMucTK")]
	public partial class HangMucTK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHangMucTK;
		
		private string _TenHangMucTK;
		
		private int _CongTrinhID;
		
		private string _MaHieuCT;
		
		private string _NguoiTao;
		
		private System.DateTime _NgayTao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangMucTKChanging(int value);
    partial void OnMaHangMucTKChanged();
    partial void OnTenHangMucTKChanging(string value);
    partial void OnTenHangMucTKChanged();
    partial void OnCongTrinhIDChanging(int value);
    partial void OnCongTrinhIDChanged();
    partial void OnMaHieuCTChanging(string value);
    partial void OnMaHieuCTChanged();
    partial void OnNguoiTaoChanging(string value);
    partial void OnNguoiTaoChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public HangMucTK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHangMucTK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHangMucTK
		{
			get
			{
				return this._MaHangMucTK;
			}
			set
			{
				if ((this._MaHangMucTK != value))
				{
					this.OnMaHangMucTKChanging(value);
					this.SendPropertyChanging();
					this._MaHangMucTK = value;
					this.SendPropertyChanged("MaHangMucTK");
					this.OnMaHangMucTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHangMucTK", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TenHangMucTK
		{
			get
			{
				return this._TenHangMucTK;
			}
			set
			{
				if ((this._TenHangMucTK != value))
				{
					this.OnTenHangMucTKChanging(value);
					this.SendPropertyChanging();
					this._TenHangMucTK = value;
					this.SendPropertyChanged("TenHangMucTK");
					this.OnTenHangMucTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongTrinhID", DbType="Int NOT NULL")]
		public int CongTrinhID
		{
			get
			{
				return this._CongTrinhID;
			}
			set
			{
				if ((this._CongTrinhID != value))
				{
					this.OnCongTrinhIDChanging(value);
					this.SendPropertyChanging();
					this._CongTrinhID = value;
					this.SendPropertyChanged("CongTrinhID");
					this.OnCongTrinhIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHieuCT", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string MaHieuCT
		{
			get
			{
				return this._MaHieuCT;
			}
			set
			{
				if ((this._MaHieuCT != value))
				{
					this.OnMaHieuCTChanging(value);
					this.SendPropertyChanging();
					this._MaHieuCT = value;
					this.SendPropertyChanged("MaHieuCT");
					this.OnMaHieuCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiTao", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string NguoiTao
		{
			get
			{
				return this._NguoiTao;
			}
			set
			{
				if ((this._NguoiTao != value))
				{
					this.OnNguoiTaoChanging(value);
					this.SendPropertyChanging();
					this._NguoiTao = value;
					this.SendPropertyChanged("NguoiTao");
					this.OnNguoiTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
